### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Timong-craft** [Einkornwolf/Pterodactyl-Discord-Manager#1]
**Die Sprache**
An den meisten stellen ist es Englisch, aber an manchen stellen Deutsch, dass ist etwas verwirrend

**Comment by Timong-craft** [comment]
Aber das ist echt ein nicer Bot

**Comment by Einkornwolf** [comment]
Danke,
Eine Language Funktion ist in Arbeit, dann ist der Bot komplett in der jeweiligen vom Nutzer eingestellten Sprache. 
Mfg

**Comment by Timong-craft** [comment]
Jo, alles klar
